Some f-strings in utils.py are broken (missing the letter "f")
amaranth-lang/amaranth pull request #1196
Opened 2024-03-11 19:45 UTC by mcclure

Without this patch, `exact_log2(3)` will print `"{n} is not a power of 2"` instead of `"3 is not a power of 2"` as intended

2024-03-11 19:57 UTC, whitequark approved these changes

2024-03-11 19:58 UTC, whitequark commented
Actually, care to add a test?

2024-03-11 19:58 UTC, whitequark commented
Also, your commit message should be formatted something like

    utils: F-strings are missing the letter "f"

2024-03-13 04:15 UTC, mcclure commented
Did a forced push with a corrected summary plus a test.

I tested with `pdm install && pdm run test` and although I am almost totally certain the test is correct and passes, I'm not sure I ran the tests right because I got 10 failures in other areas. I think this test is right though because when I changed "not" to "nfot" in the test string the failure count went up to 11 :P

2024-03-13 04:20 UTC, wanda-phi commented
> Did a forced push with a corrected summary plus a test.
> 
> I tested with `pdm install && pdm run test` and although I am almost totally certain the test is correct and passes, I'm not sure I ran the tests right because I got 10 failures in other areas. I think this test is right though because when I changed "not" to "nfot" in the test string the failure count went up to 11 :P

I don't actually see any test?

2024-03-13 05:34 UTC, whitequark requested changes

2024-03-13 05:34 UTC, whitequark commented on tests/test_utils.py
> +            with self.assertRaisesRegex(ValueError, (f"^{val} is not a power of 2$")):
One for `ceil_log2` too please.

2024-03-13 14:49 UTC, mcclure commented
Apologies, should have got that the first time.

2024-03-13 14:56 UTC, whitequark approved these changes

2024-03-13 15:02 UTC, merged