hdl._nir: add combinational cycle detection.
amaranth-lang/amaranth pull request #1330
Opened 2024-04-13 11:40 UTC by wanda-phi

Fixes #704.
Fixes #1143.

2024-04-13 13:39 UTC, whitequark commented on tests/test_hdl_ir.py
> +        with self.assertRaises(CombinationalCycle):
This should probably assert on a message using `assertRaisesRegex` to skip the variable parts like the line numbers.

2024-04-13 13:40 UTC, whitequark commented on amaranth/hdl/_nir.py
> +    def comb_edges_to(self, bit: int) -> Iterable[Net]:
The annotation on the base class is probably sufficient.

2024-04-13 13:40 UTC, whitequark commented on amaranth/hdl/_nir.py
> +    def comb_edges_to(self, bit: int) -> Iterable[Net]:
Likewise.

2024-04-13 13:43 UTC, whitequark commented on amaranth/hdl/_nir.py
> +                            raise
Please use a local return instead of a nonlocal return, since using a nonlocal return adds nothing.

2024-04-13 13:48 UTC, whitequark requested changes
See inline comments.

2024-04-13 13:54 UTC, whitequark approved these changes
LGTM, thanks!

2024-04-13 14:07 UTC, merged

2024-04-14 09:11 UTC, widlarizer commented
Sweet!