Documentation: Changing "combinatorial" to "combinational"
amaranth-lang/amaranth pull request #1332
Opened 2024-04-13 20:45 UTC by X-Illuminati

Resolves #1301

The first two commits update the documentation and are simple find-and-replace in python docstrings and rst, respectively.
When rebasing, an additional search may be needed.

The third commit adds additional content and should be reviewed by project maintainers more closely.

2024-04-13 20:52 UTC, whitequark requested changes
- Please rebase on top of https://github.com/amaranth-lang/amaranth/pull/1333 once it's in (I completely forgot that it was on a branch and not merged).
- Please move your style guide sentence to the section added in #1333.
- Please squash all commits.
- It's not necessary to add a compatibility anchor.

2024-04-13 20:52 UTC, X-Illuminati commented
@whitequark , ready for review

2024-04-13 20:56 UTC, X-Illuminati commented
@whitequark , heh you are too quick for me. Will take a look at #1333 and rebase.

2024-04-14 22:55 UTC, whitequark commented on docs/contrib.rst
> +* It is preferred to use the term "combinational" rather than "combinatorial" to refer to non-sequential logic. See `Issue #1301`_ for more details.
```suggestion
* To refer to non-sequential logic, use the term "combinational" over "combinatorial".
```

(A style guide's purpose is to set the standard. It is stronger than a mere _preference_--you are required to use this term when contributing--and it's also not particularly important what the reasoning is, just like for all other items here.)

2024-04-15 22:36 UTC, X-Illuminati commented
@whitequark rebased and ready for review

2024-04-16 02:18 UTC, whitequark approved these changes
Thanks!

2024-04-16 02:25 UTC, merged