Lattice: Add support for MachXO2/XO3L internal oscillator
amaranth-lang/amaranth pull request #575
Opened 2021-01-13 00:26 UTC by jreyesr

This PR adds support for the internal high-speed oscillator on MachXO2/XO3L devices, called OSCH. Migen had support for the oscillator, but nMigen doesn't have it yet.

It essentially replicates the changes that https://github.com/nmigen/nmigen/pull/530 made on Intel Cyclone V devices, with the difference that MachXO2/XO3 devices have a configurable frequency, as opposed to the Cyclone V which has a fixed frequency with a maximum of 100MHz.

This PR is accompanied by PR \<TODO, will add once the PR is actually published\> in nmigen-boards, which changes the TinyFPGAAX2Platform to use the internal clock (at 2.08 MHz) by default, since the TinyFPGA AX2 has no external clock and thus no better default alternative for the clock signal.

2021-01-29 02:39 UTC, whitequark requested changes
Our other platforms that support a configurable internal clock source, iCE40, ECP5, and QuickLogic, use a divider to set the frequency. This simplifies the logic, in particular it means that any input configuration exactly (within the limits of the hardware) specifies output frequency. In addition, ECP5 uses the same cell library as MachXO2/XO3L and is a broadly similar family of devices, so they should definitely use the same general approach.

Please change your implemenation to closely follow the logic in the ECP5 platform.

2021-01-30 01:50 UTC, jreyesr commented
There's a difference between iCE40, ECP5, and QuickLogic devices, on the one hand, and MachXO2, on the other. On MachXO2 devices, the oscillator is configured by explicitly setting the frequency as a Verilog parameter. See [pages 35 to 37 here](http://www.latticesemi.com/~/media/LatticeSemi/Documents/ApplicationNotes/MO/MachXO2sysCLOCKPLLDesignandUsageGuide.pdf?document_id=39080) for an example. 

The allowed frequencies _do_ seem to come from a 266 MHz oscillator with a configurable divider with ratios between 2 to 128 (this is not in the documentation, it simply fits the list provided and you can't set the oscillator frequency by passing a divider). Hovewer, not all ratios are valid. Ratios 2 to 32 are all valid, ratios between 32 to 64 are only valid if divisible by 2, and ratios between 64 and 128 are valid if divisible by 4.

Should I still go ahead and use a divider ratio as the configurable parameter, as opposed to the raw frequency that is now being used? If so, there will still be "dead spots" in the input values (i.e., it won't be enough to just "enter a divider between 2 and 128", as in the other families, since, say, 65 would request a frequency of 4.09 MHz, which is not in the list of valid frequencies). Is that acceptable?

2021-02-03 00:31 UTC, whitequark commented
> Should I still go ahead and use a divider ratio as the configurable parameter, as opposed to the raw frequency that is now being used?

No, with this additional information, I believe your approach is correct. I'll take another look soon.

2021-12-11 14:11 UTC, modwizcode submitted a review, later dismissed
LGTM, just needs to be rebased I think.

2021-12-11 21:36 UTC, jreyesr commented
> LGTM, just needs to be rebased I think.

Done. I just made a brand new commit, since my code was outdated by almost a year.

2022-04-06 04:10 UTC, modwizcode approved these changes
Thanks for rebasing.

2022-04-06 04:11 UTC, whitequark approved these changes
LGTM

2022-04-06 04:12 UTC, merged

2022-04-06 04:13 UTC, whitequark commented
Thank you, and apologies for the delay!

2022-04-06 13:11 UTC, jreyesr commented
> Thank you, and apologies for the delay!

Of course, no worries. Thank you!