[WIP/PoC] Add async testbench functions
amaranth-lang/amaranth pull request #990
Opened 2023-12-06 20:51 UTC by zyp

2024-03-21 21:23 UTC, whitequark requested changes
So I don't think we can really commit to this approach because it implements the new interface in terms of the old one and we want to deprecate and remove the old one. (We also want the new one to have *less* overhead, not more.)

2024-03-21 21:52 UTC, zyp commented
I'm not intending to *commit* to this approach, but I think it'd be useful to prototype a simple working implementation first and write a suite of passing tests against it before starting on the «real» implementation.

2024-03-21 21:55 UTC, whitequark commented
Yeah, no objection to that, of course.

2024-05-06 11:11 UTC, whitequark commented
Thank you for this work, @zyp! PR #1344 supersedes this PR with a more complete implementation. We have ended up rewriting a lot of the simulator internals, as well as filling in the blanks in a few places where the RFC was unimplementable or underspecified.

2024-05-06 11:11 UTC, closed without merging